### ISSUE TITLE
seems like https://oor.lu/ is down

### ISSUE THREAD

**Issue by pekcheey** [adamwojt/oorlu-cli#1]
**Describe the bug**
https://oor.lu/ is down 

**To Reproduce**
1.  see below 

> curl https://oor.lu/
curl: (6) Could not resolve host: oor.lu

This means that previously generated link will not work anymore.

**Comment by adamwojt** [comment]
Right. Thanks for reminding me about this repo. I unfortunately lost the domain due misunderstanding with my provider side. I will think of something. Meanwhile you could try to self host https://github.com/adamwojt/ur_l and adjust your API link here https://github.com/adamwojt/oorlu-cli/blob/1bb5d5a65ca3113b627d1554766a3ddc8a624f4c/src/oorlu_cli/oorlu.py#L4

**Comment by adamwojt** [comment]
After some thinking I decided I won't be continuing to provide oorlu instance :( Sorry about this, I hope that both https://github.com/adamwojt/oorlu-cli and https://github.com/adamwojt/ur_l can be reused by someone though.

**Comment by adamwojt** [comment]
@pekcheey we are back, I got domain back.
